### ISSUE TITLE
Click on settings closes app

### ISSUE THREAD

**Issue by lwndp** [byrencheema/airstats#2]
Steps to reproduce:

1. Open Airstats
2. Click to open flyout menu from menu bar
3. Click on settings (lower left)

**Comment by 0xPIT** [comment]
The App actually crashes:

AirStatUI/resource_bundle_accessor.swift:12: Fatal error: could not load resource bundle: from /Applications/AirStats.app/AirStats_AirStatUI.bundle or /Users/byrencheema/coding/personalprojects/airstat/.build/arm64-apple-macosx/release/AirStats_AirStatUI.bundle
[1]    52175 trace trap  /Applications/AirStats.app/Contents/MacOS/AirStats

**Comment by byrencheema** [comment]
Thanks for the report, and thanks @0xPIT for the crash log. I reproduced the crash and traced it to the UI resource bundle being packaged where the runtime could not find it.

This is fixed in [AirStats 1.2.1](https://github.com/byrencheema/airstats/releases/tag/v1.2.1). I verified the original steps on a clean install and tested updating from 1.2 through Sparkle.

You can update in AirStats or run:

```sh
brew upgrade --cask airstats
```

Please comment if Settings still crashes after updating to 1.2.1.
